# artifact-upload.yml
---
name: Artifact Upload

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  create-artifact:
    env:
      ARTIFACT_NAME: artifact.txt
      ARTIFACT_PATH: ./
    runs-on: ubuntu-latest
    steps:

      - name: Create something to artifact
        run: |

          # Here we just create something for the example
          echo "stuff I want to artifact" > "$ARTIFACT_PATH/$ARTIFACT_NAME"

      - name: Upload Artifact
        id: upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}/${{ env.ARTIFACT_NAME }}
          if-no-files-found: error
          
      - name: Get Artifact URL & PR Info
        env:
          GITHUB_TOKEN: ${{ github.token }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.repository.name }}
        run: |
        
          PREVIOUS_JOB_ID=github.event.workflow_run.id
          echo "Previous Job ID: $PREVIOUS_JOB_ID"
          echo "PREVIOUS_JOB_ID=$PREVIOUS_JOB_ID" >> "$GITHUB_ENV"

          ARTIFACT_URL=$(gh api "/repos/$OWNER/$REPO/actions/artifacts" \
            --jq ".artifacts.[] |
            select(.workflow_run.id==${PREVIOUS_JOB_ID}) |
            select(.expired==false) |
            .archive_download_url")

          echo "ARTIFACT URL: $ARTIFACT_URL"
          echo "ARTIFACT_URL=$ARTIFACT_URL" >> "$GITHUB_ENV"

          PR_NUMBER= github.event.pull_request.number

          echo "PR Number: $PR_NUMBER"
          echo "PR_NUMBER=$PR_NUMBER" >> "$GITHUB_ENV"

          HEAD_SHA= github.event.head.sha

          echo "Head sha: $HEAD_SHA"
          echo "HEAD_SHA=$HEAD_SHA" >> "$GITHUB_ENV"

      - name: Update Comment
        env:
          JOB_PATH: "${{ github.server_url }}/${{ github.repository }}/actions/\
            runs/${{ env.PREVIOUS_JOB_ID }}"
          HEAD_SHA: ${{ env.HEAD_SHA }}
        uses: peter-evans/create-or-update-comment@v3.0.2
        with:
          issue-number: ${{ env.PR_NUMBER }}
          body: |-
            ## Build Preview

            [![badge]]($JOB_PATH)

            You can find files attached to the below linked Workflow Run URL (Logs).

            Please note that files only stay for around 90 days!

            | Name      | Link
            --------------------------------------------------------------------
            | Commit    | ${{ env.HEAD_SHA }}

            | Logs      | ${{ env.JOB_PATH }}

            | Jar Files | ${{ env.ARTIFACT_URL }}

            [badge]: https://img.shields.io/badge/Build-Success!-3fb950?logo=github&style=for-the-badge                    
          

