# pr-comment-artifact-url.yml
---
name: Comment Artifact URL on PR

on:
  workflow_run:
    workflows: [Artifact Upload]
    types: [completed]

jobs:
  comment-on-pr:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:

      - name: Get Artifact URL & PR Info
        
        run: |
          echo 'SUCCESS'