# pr-comment-artifact-url.yml
---
name: Delete Artifact URL in PR

on:
  workflow_run:
    types:
      - "requested"
    workflows:
      - "Artifact Upload"
    branches-ignore:
      - "main"

permissions:
  contents: read
  pull-requests: write

jobs:
  delete-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.number }}
          comment-author: 'github-actions[bot]'
      - name: Update Comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.number }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          body: |-
            ![badge]
            
            Replacing build
